import type { NextPage } from 'next';
import Head from 'next/head';
import Nav from '../components/Nav/Nav';
import Footer from '../components/Footer/Footer';
import Hero from '../components/Hero/Hero';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='h-screen w-full px-10 py-5 bg-white text-black dark:bg-zinc-900 dark:text-white transition-colors ease-in-out delay-200'>
				<Nav />
				<Hero />
			</main>
			<Footer />
		</div>
	)
}

export default Home;